-- type
-- 문제: varchar(200), char, text, CLOB(Character Large OBject)
-- 정수: medium int, int(signed, integer), unsigned, big int
-- 실수: float, double,
-- 시간: data, datetime
-- LOB: CLOB, BLOB(Binary Large OBject)